### ISSUE TITLE
How to use your finetuned model ?

### ISSUE THREAD

**Issue by maepopi** [metavoiceio/metavoice-src#110]
Hey there! I've originally posted this question inside of a longer thread but I thought it might be best to post it as a new thread because I'm unlikely to be the only one to have this issue.

So I've gone ahead and finetuned my first model, but I don't get how I can use it now. I went to see into the "fast_inference.py" and I saw a checkpoint path at line 88 but I got an OOM when trying to point to my finetuned ckpt. So I'm not sure I'm doing it right (not surprising since there is an entire rig to load the model from Hugging Face so that was kind of a desperate attempt on my part!)

I've also tried changing the checkpoint path in the "inference.py" script, but I have another OOM error.

Thanks!!

**Comment by vatsalaggarwal** [comment]
Does finetuning run on that same GPU though? That's a bit strange because it looks like you do have enough VRAM for weights+optimiser states?

**Comment by maepopi** [comment]
Hey!! Thanks for your answer!

Well yes, I think the finetuning ran on that same GPU because I think I saw in the console that the finetuning was run on GPU = 0 (which I thought, at the time,  was the index of the device used) and CUDA was called. AND the training was relatively fast, which would definitely not have been the case on CPU I think

I have a RTX 3060 12Gb, here is the exact message have:


"<html>
<body>
<div class="aju" style="cursor: default; align-items: center; display: flex; float: none; height: 80px; padding: 0px 16px; min-width: 40px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aCi" style="position: relative;"><img id=":oy_3-e" name=":oy" src="https://lh3.googleusercontent.com/a/ACg8ocKdVyhY6Ijg5_r0Xwq7abNFBVciMnMFoGfc9swf92j0=s40-p-mo" class="ajn" jid="maelys.jusseaux@gmail.com" data-hovercard-id="maelys.jusseaux@gmail.com" data-name="Maëlys Jusseaux" aria-hidden="true" style="width: 40px; height: 40px; border-radius: 50%; display: block; background-color: rgb(204, 204, 204);"></div></div><div class="gs" style="margin: 0px; min-width: 0px; padding: 0px 0px 20px; width: initial; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gE iv gt" style="font-size: 0.875rem; cursor: auto; padding: 20px 0px 0px;">
Maëlys Jusseaux <maelys.jusseaux@gmail.com> | Maëlys Jusseaux <maelys.jusseaux@gmail.com> | 15:25 (il y a 0 minute) |   |  
-- | -- | -- | -- | --
Maëlys Jusseaux <maelys.jusseaux@gmail.com>
À moi | À moi
À moi

</div><div id=":2xz"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="wl4W9b" jsaction="LNSvUb:.CLIENT;xSdBYb:.CLIENT;CDWmBe:.CLIENT;EtHLdc:.CLIENT;pQnh7:.CLIENT;pKHw7e:.CLIENT;Z03mxd:.CLIENT;NZLNxf:.CLIENT;bXglpe:.CLIENT;mzh2Bc:.CLIENT" style="display: flex;"></div></div><div class=""><div class="aHl" style="margin-left: -38px;"></div><div id=":2ym" tabindex="-1"></div><div id=":2xx" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWE6ci01NTc0ODE3MDg1MTQ3MzgxMDUyfG1zZy1hOnItNTU3OTc3NDUzNDc5NzQzMzQzNiJd; 4:WyIjbXNnLWE6ci01NTc5Nzc0NTM0Nzk3NDMzNDM2Il0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem; overflow-x: hidden;"><div id=":2xy" class="a3s aiL " style="direction: initial; font: small / 1.5 Arial, Helvetica, sans-serif; overflow: auto hidden; position: relative;"><div dir="ltr">Traceback (most recent call last):<br>  File "/home/maelys/AI_PROJECTS/<wbr>SOUND/TOOLS/metavoice-src/fam/<wbr>llm/fast_inference.py", line 161, in &lt;module&gt;<br>    tts = tyro.cli(TTS)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/tyro/_cli.py", line 187, in cli<br>    output = _cli_impl(<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/tyro/_cli.py", line 454, in _cli_impl<br>    out, consumed_keywords = _calling.call_from_args(<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/tyro/_calling.py", line 241, in call_from_args<br>    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore<br>  File "/home/maelys/AI_PROJECTS/<wbr>SOUND/TOOLS/metavoice-src/fam/<wbr>llm/fast_inference.py", line 80, in __init__<br>    self.llm_second_stage = Model(<br>  File "/home/maelys/AI_PROJECTS/<wbr>SOUND/TOOLS/metavoice-src/fam/<wbr>llm/inference.py", line 93, in __init__<br>    self._init_model()<br>  File "/home/maelys/AI_PROJECTS/<wbr>SOUND/TOOLS/metavoice-src/fam/<wbr>llm/inference.py", line 141, in _init_model<br>   <span> </span><a href="http://self.model.to/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://self.model.to&amp;source=gmail&amp;ust=1711463132874000&amp;usg=AOvVaw3ZZd_bWCucemKxX4vWlJ73" style="color: rgb(17, 85, 204);">self.model.to</a>(self.config.<wbr>device)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 1152, in to<br>    return self._apply(convert)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 802, in _apply<br>    module._apply(fn)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 802, in _apply<br>    module._apply(fn)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 802, in _apply<br>    module._apply(fn)<br>  [Previous line repeated 3 more times]<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 825, in _apply<br>    param_applied = fn(param)<br>  File "/home/maelys/.cache/pypoetry/<wbr>virtualenvs/fam-QegjHbyx-py3.<wbr>10/lib/python3.10/site-<wbr>packages/torch/nn/modules/<wbr>module.py", line 1150, in convert<br>    return<span> </span><a href="http://t.to/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://t.to&amp;source=gmail&amp;ust=1711463132874000&amp;usg=AOvVaw3w2Q02LF-WiQTMBBzqDjT9" style="color: rgb(17, 85, 204);">t.to</a>(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)<br>torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB. GPU 0 has a total capacity of 11.76 GiB of which 55.25 MiB is free. Process 4518 has 336.64 MiB memory in use. Including non-PyTorch memory, this process has 10.85 GiB memory in use. Of the allocated memory 10.66 GiB is allocated by PyTorch, and 58.62 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=<wbr>expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (<a href="https://pytorch.org/docs/stable/notes/cuda.html#environment-variables" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pytorch.org/docs/stable/notes/cuda.html%23environment-variables&amp;source=gmail&amp;ust=1711463132874000&amp;usg=AOvVaw2YiyRkQwANohAYNbTBCYfG" style="color: rgb(17, 85, 204);">https://pytorch.org/docs/<wbr>stable/notes/cuda.html#<wbr>environment-variables</a>)</div></div></div></div></div>
</body>
</html>
Maëlys Jusseaux <maelys.jusseaux@gmail.com>
15:25 (il y a 0 minute)
À moi

Traceback (most recent call last):
  File "/home/maelys/AI_PROJECTS/SOUND/TOOLS/metavoice-src/fam/llm/fast_inference.py", line 161, in <module>
    tts = tyro.cli(TTS)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/tyro/_cli.py", line 454, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/tyro/_calling.py", line 241, in call_from_args
    return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
  File "/home/maelys/AI_PROJECTS/SOUND/TOOLS/metavoice-src/fam/llm/fast_inference.py", line 80, in __init__
    self.llm_second_stage = Model(
  File "/home/maelys/AI_PROJECTS/SOUND/TOOLS/metavoice-src/fam/llm/inference.py", line 93, in __init__
    self._init_model()
  File "/home/maelys/AI_PROJECTS/SOUND/TOOLS/metavoice-src/fam/llm/inference.py", line 141, in _init_model
    [self.model.to](http://self.model.to/)(self.config.device)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/maelys/.cache/pypoetry/virtualenvs/fam-QegjHbyx-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return [t.to](http://t.to/)(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB. GPU 0 has a total capacity of 11.76 GiB of which 55.25 MiB is free. Process 4518 has 336.64 MiB memory in use. Including non-PyTorch memory, this process has 10.85 GiB memory in use. Of the allocated memory 10.66 GiB is allocated by PyTorch, and 58.62 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)"


I tried a torch.cuda.empty_cache() but to no avail :'(

**Comment by vatsalaggarwal** [comment]
yeah, torch.cuda.empty_cache is unlikely to help here... if you've got 15-16 GBs of GPU RAM, you can try add `map_location="cpu"` to https://github.com/metavoiceio/metavoice-src/blob/main/fam/llm/fast_inference_utils.py#L243 ...

otherwise, the best thing to do might be to remove saving optimiser states during checkpointing ... you basically need to remove this line: https://github.com/metavoiceio/metavoice-src/blob/main/fam/llm/finetune.py#L288 ... but you might have difficultly resuming your finetuning jobs if you ever want to do that...

**Comment by maepopi** [comment]
Oh yeah there's really no way to resume the finetuning on 12GB VRAM (aka save the optimiser states if I understand correctly)? 
It's okay let me just try that for now and see whether it helps

**Comment by maepopi** [comment]
I suppose I have to first delete the line in finetune.py, THEN retrain my model, and then try to call it through inference.py? Is that right? 
(Sorry I'm still a novice in all this :))

**Comment by vatsalaggarwal** [comment]
Yeah, that's the "easiest"... the way to use your existing training is to "add `map_location="cpu"` to https://github.com/metavoiceio/metavoice-src/blob/main/fam/llm/fast_inference_utils.py#L243"

**Comment by maepopi** [comment]
Ok this would then make the inference tap into the CPU to compensate for the lack of VRAM is that it?
And if I retrain my model without the optimizer save, then I don't need to add ```map_location="cpu"``` because I'd have enough VRAM, is that it?

thank you so much for your patience

**Comment by vatsalaggarwal** [comment]
it would just mean that the optimiser states remain in CPU RAM instead of living on GPU. Model should still be on GPU.

**Comment by maepopi** [comment]
OK! let me try both solutions and get back to you later today :)

**Comment by maepopi** [comment]
Hey again!
So unfortunately I still have the OOM problem :( here's what I tried :
- I added the map_location="cpu" line to "fast_inference_utils.py", wrote the path to my _former_ finetuned model in "fast_inference.py", and then launched ```poetry run python -i fam/llm/fast_inference.py``` => OOM
- I commented the optimizer save in the finetune.py script, retrained the model, and then tried the first step again but this time pointing to the new finetuned model ==> OOM
- I tried to run the fast inference command without the "map_location" line ==> OOM

thanks!

**Comment by vatsalaggarwal** [comment]
sorry about the issues here :( we'll have a look today/tomorrow!

**Comment by maepopi** [comment]
No worries, thank you for your implication :)))

**Comment by vatsalaggarwal** [comment]
hey, sorry about the delay here... i'm looking into this now... could you share your finetuned checkpoint with me please, and also which GPU you were using?

**Comment by maepopi** [comment]
Hey @vatsalaggarwal any news on this question? Have you received my checkpoint?

Thank you! I'm such in a hurry to start finetuning and try my hand at making a French model!

**Comment by lucapericlp** [comment]
@vatsalaggarwal anything worth adding here?

**Comment by maepopi** [comment]
Hey there! I was wondering whether there was anything new on that front? @vatsalaggarwal have you had some time to investigate why my checkpoint didn't work?
