### ISSUE TITLE
TypeError: 'type' object is not subscriptable on running sample.py

### ISSUE THREAD

**Issue by leocd91** [metavoiceio/metavoice-src#15]
Hi,

Just followed your installation step and when I tried the following command:
`python fam/llm/sample.py --huggingface_repo_id="metavoiceio/metavoice-1B-v0.1" --spk_cond_path="assets/ava.flac"`

The results are: 
```
Traceback (most recent call last):
  File "fam/llm/sample.py", line 19, in <module>
    from fam.llm.adapters import FlattenedInterleavedEncodec2Codebook, TiltedEncodec
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/__init__.py", line 1, in <module>
    from fam.llm.adapters.flattened_encodec import FlattenedInterleavedEncodec2Codebook
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/flattened_encodec.py", line 4, in <module>
    class FlattenedInterleavedEncodec2Codebook(BaseDataAdapter):
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/flattened_encodec.py", line 8, in FlattenedInterleavedEncodec2Codebook
    def decode(self, tokens: list[list[int]]) -> tuple[list[int], list[list[int]]]:
TypeError: 'type' object is not subscriptable
```

Thank you

**Comment by vatsalaggarwal** [comment]
It’s likely related to the Python version… you can upgrade to a newer version or replace the type hint with corresponding types from typing libraryOn Feb 8, 2024, at 12:07 AM, Leo Cahya Dinendra ***@***.***> wrote:﻿
Hi,
Just followed your installation step and when I tried the following command:
python fam/llm/sample.py --huggingface_repo_id="metavoiceio/metavoice-1B-v0.1" --spk_cond_path="assets/ava.flac"
The results are:
Traceback (most recent call last):
  File "fam/llm/sample.py", line 19, in <module>
    from fam.llm.adapters import FlattenedInterleavedEncodec2Codebook, TiltedEncodec
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/__init__.py", line 1, in <module>
    from fam.llm.adapters.flattened_encodec import FlattenedInterleavedEncodec2Codebook
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/flattened_encodec.py", line 4, in <module>
    class FlattenedInterleavedEncodec2Codebook(BaseDataAdapter):
  File "/home/leocd/metavoice/metavoice-src/fam/llm/adapters/flattened_encodec.py", line 8, in FlattenedInterleavedEncodec2Codebook
    def decode(self, tokens: list[list[int]]) -> tuple[list[int], list[list[int]]]:
TypeError: 'type' object is not subscriptable

Thank you

**Comment by sidroopdaska** [comment]
Yes, upto python 3.10 should work

**Comment by Jainish-S** [comment]
@lorenzosciuto I have checked and python 3.9, 3.10, 3.11 works

**Comment by lorenzosciuto** [comment]
as far as I can see with python 3.8 will not work.

**Comment by sidroopdaska** [comment]
Added python version with #34. Closing this issue now.
