### ISSUE TITLE
Encoder checkpoint missing

### ISSUE THREAD

**Issue by tvergho** [metavoiceio/metavoice-src#3]
When cloning the repo and running just the sample code (`python fam/llm/sample.py --huggingface_repo_id="metavoiceio/metavoice-1B-v0.1" --spk_cond_path="assets/ava.flac"`) without any changes, the model successfully downloads but I get the following error:

```
Fetching 5 files: 100%|█████████████████████████| 5/5 [00:00<00:00, 8053.58it/s]
Traceback (most recent call last):
  File "/kaggle/working/metavoice-src/fam/llm/sample.py", line 690, in <module>
    smodel, llm_first_stage, llm_second_stage = build_models(
  File "/kaggle/working/metavoice-src/fam/llm/sample.py", line 563, in build_models
    smodel = SpeakerEncoder(device=device, eval=True, verbose=False)
  File "/kaggle/working/metavoice-src/fam/quantiser/audio/speaker_encoder/model.py", line 50, in __init__
    checkpoint = torch.load(weights_fpath, map_location="cpu")
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/metavoice-src/fam/quantiser/audio/speaker_encoder/ckpt/ckpt.pt'
```

Is there a separate encoder checkpoint that's needed for this to work?

**Comment by sidroopdaska** [comment]
Thanks for flagging this, I'm looking into it

**Comment by sidroopdaska** [comment]
@tvergho, PR #5 fixes this issue

**Comment by tvergho** [comment]
@sidroopdaska Thank you!

**Comment by MethanJess** [comment]
@tvergho Hey! I've noticed that you're using kaggle, 
Could you please share your metavoice kaggle notebook? I really stuggled to make it work on kaggle..
