### ISSUE TITLE
Typing error with Python 3.9 (`TypeError: unsupported operand type(s) for ...`)

### ISSUE THREAD

**Issue by paulrogov** [metavoiceio/metavoice-src#31]
**Python 3.9.15**  
Trying to execute the `sample.py` produced 3 typing errors. I had just removed type annotations and it proceeded to the next step (huggingface credentials verification).

Please specify Python version or remove these type annotations (as I did).

```bash
python fam/llm/sample.py --huggingface_repo_id="metavoiceio" --spk_cond_path="assets/bria.mp3"
2024-02-09 19:17:47.280515: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/paul/myapps/data_science/text-to-speech/metavoice-src/fam/llm/sample.py", line 21, in <module>
    from fam.llm.decoders import Decoder, EncodecDecoder
  File "/home/paul/myapps/data_science/text-to-speech/metavoice-src/fam/llm/decoders.py", line 19, in <module>
    class EncodecDecoder(Decoder):
  File "/home/paul/myapps/data_science/text-to-speech/metavoice-src/fam/llm/decoders.py", line 66, in EncodecDecoder
    ) -> str | torch.Tensor:
TypeError: unsupported operand type(s) for |: 'type' and 'torch._C._TensorMeta'
```

```bash
python fam/llm/sample.py --huggingface_repo_id="metavoiceio" --spk_cond_path="assets/bria.mp3"
2024-02-09 19:20:55.558639: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
/home/paul/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
Traceback (most recent call last):
  File "/home/paul/myapps/data_science/text-to-speech/metavoice-src/fam/llm/sample.py", line 455, in <module>
    enhancer: Optional[Literal["df"] | BaseEnhancer],
TypeError: unsupported operand type(s) for |: '_LiteralGenericAlias' and 'ABCMeta'
```

```bash
 python fam/llm/sample.py --huggingface_repo_id="metavoiceio" --spk_cond_path="assets/bria.mp3"
2024-02-09 19:23:50.126062: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
/home/paul/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
Traceback (most recent call last):
  File "/home/paul/myapps/data_science/text-to-speech/metavoice-src/fam/llm/sample.py", line 533, in <module>
    enhancer: Optional[Literal["df"] | BaseEnhancer],
TypeError: unsupported operand type(s) for |: '_LiteralGenericAlias' and 'ABCMeta'
```

**Comment by fakerybakery** [comment]
Running into the same error

**Comment by sidroopdaska** [comment]
Please review #34 
I add details on python version

**Comment by sidroopdaska** [comment]
@fakerybakery, what python version are you using?

**Comment by fakerybakery** [comment]
3.9

**Comment by sidroopdaska** [comment]
added python version to be >= 3.10, <3.12 in #34, i have also reverted the typings to use Union over the `|` operator.
closing this issue
