### ISSUE TITLE
I created a working Dockerfile to build it consistently (and on my system)...

### ISSUE THREAD

**Issue by groovybits** [metavoiceio/metavoice-src#48]
Hi I created this Dockerfile just now to make building easier (and allow it on my system where Python seems unhappy, Mac)...

I am wondering about if this could be included and improved upon since I haven't gotten it running locally yet but at least got it built for me...

Branch with changes: https://github.com/metavoiceio/metavoice-src/compare/main...groovybits:metavoice-src:docker

Also I am wondering about which port it uses and how to use this? Or more information on how to use it locally like an http server if this is what does that?

Thanks! I am reading up / exploring as I can since this looks amazing :)

Updated: builds in docker compose now, not sure if "working" yet (need to look closer).

**Comment by sidroopdaska** [comment]
sure thing, will review it tomorrow morning

**Comment by djmaze** [comment]
I think it's [port 58003](https://github.com/metavoiceio/metavoice-src/blob/main/fam/llm/serving.py#L59). Also, you should use `pip install -e .` for the app package to install correctly.

(Still, personally, I cannot currently make this work because of other errors.)

**Comment by sidroopdaska** [comment]
Hey @djmaze, can you share some details
1. GPU being used
2. Python version
3. Error you are facing

**Comment by groovybits** [comment]
I updated the docker setup and it builds and runs but I see this... (still investigating)

```
(.venv) chris@earth metavoice-src % docker compose up --build
[+] Building 153.2s (12/12) FINISHED                                                                                                                  docker:desktop-linux
 => [metavoice-server internal] load .dockerignore                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                       0.0s
 => [metavoice-server internal] load build definition from Dockerfile                                                                                                 0.0s
 => => transferring dockerfile: 920B                                                                                                                                  0.0s
 => [metavoice-server internal] load metadata for docker.io/library/python:3.11-slim                                                                                  0.3s
 => [metavoice-server 1/7] FROM docker.io/library/python:3.11-slim@sha256:0b7568850e62c6405d15098486b8fc23d9d6a845b112b866aceaf65fbded2fc1                            0.0s
 => [metavoice-server internal] load build context                                                                                                                    0.9s
 => => transferring context: 3.26MB                                                                                                                                   0.8s
 => CACHED [metavoice-server 2/7] RUN apt-get update && apt-get install -y     ffmpeg     ninja-build     g++     build-essential     libomp-dev     && rm -rf /var/  0.0s
 => CACHED [metavoice-server 3/7] WORKDIR /app                                                                                                                        0.0s
 => [metavoice-server 4/7] COPY . .                                                                                                                                   2.2s
 => [metavoice-server 5/7] RUN pip install --no-cache-dir "torch>=2.1.0"                                                                                             10.0s
 => [metavoice-server 6/7] RUN MAX_JOBS=1 pip install --no-cache-dir -r requirements.txt                                                                            133.3s
 => [metavoice-server 7/7] RUN pip install -e .                                                                                                                       4.2s
 => [metavoice-server] exporting to image                                                                                                                             2.4s
 => => exporting layers                                                                                                                                               2.4s
 => => writing image sha256:26b4dd6910b9dbef9c0ca9c20cb96d72323047456dfc0c448b5c669cd1c8a7bb                                                                          0.0s
 => => naming to docker.io/library/metavoice-src-metavoice-server                                                                                                     0.0s
[+] Running 1/0
 ✔ Container metavoice  Recreated                                                                                                                                     0.1s
Attaching to metavoice
metavoice  | /usr/local/lib/python3.11/site-packages/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
metavoice  |   from torchaudio.backend.common import AudioMetaData
metavoice  | /app/fam/llm/layers/attn.py:14: UserWarning: flash_attn not installed, make sure to replace attention mechanism with torch_attn
metavoice  |   warnings.warn("flash_attn not installed, make sure to replace attention mechanism with torch_attn")
Fetching 6 files:   0% 0/6 [00:00<?, ?it/s]downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/second_stage.pt to /.hf-cache/hub/tmps91kmwkg
metavoice  | downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/config.json to /.hf-cache/hub/tmpr_l3s9dn
metavoice  | downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/.gitattributes to /.hf-cache/hub/tmpdzzaejrq
metavoice  | downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/README.md to /.hf-cache/hub/tmp34f1vm41
metavoice  | downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/first_stage.pt to /.hf-cache/hub/tmpgt0ocpu0
metavoice  | downloading https://huggingface.co/metavoiceio/metavoice-1B-v0.1/resolve/bf8f51bb9c3c508987b37f3197e85ea93f42475e/speaker_encoder.pt to /.hf-cache/hub/tmp6_a3cfzr
README.md: 100% 2.67k/2.67k [00:00<00:00, 25.3MB/s]
.gitattributes: 100% 1.52k/1.52k [00:00<00:00, 27.1MB/s]
config.json: 100% 39.0/39.0 [00:00<00:00, 447kB/s]
speaker_encoder.pt: 100% 17.1M/17.1M [00:00<00:00, 33.1MB/s]
second_stage.pt: 100% 57.9M/57.9M [00:01<00:00, 34.9MB/s]/s]
first_stage.pt: 100% 4.97G/4.97G [00:50<00:00, 97.8MB/s]
Fetching 6 files: 100% 6/6 [00:51<00:00,  8.57s/it]MB/s]
metavoice exited with code 1377G [00:50<00:00, 108MB/s] ]
```

**Comment by sidroopdaska** [comment]
Would love for you to make a PR once you have got this exploration over the line!
Both containerisation and inference on Mac would be a very useful contribution for the community @groovybits

**Comment by groovybits** [comment]
Yes that sounds good, I have this branch that I am working off of https://github.com/metavoiceio/metavoice-src/compare/main...groovybits:metavoice-src:docker and will make a PR when it is ready. 

I have it running the server in one container, but am not sure how to use it / a test payload yet. 

I see the ui is in the fam/ui/app.py location and shows how to create a payload,  so to make it easier to test functionality I am trying to run the ui app.py now too in another container and use it to access the other but I am running into an issue with it that I see now...

```
getting cached speaker ref files:   0% 0/1 [00:00<?, ?it/s]/bin/sh: 1: curl: not found
getting cached speaker ref files:   0% 0/1 [00:00<?, ?it/s]
metavoice-server  | Error processing request {'text': 'This is a demo of text to speech by MetaVoice-1B, an open-source foundational audio model by MetaVoice.', 'guidance': 3.0, 'top_p': 0.95, 'speaker_ref_path': 'https://cdn.themetavoice.xyz/speakers/ava.flac'}
metavoice-server  | Traceback (most recent call last):
metavoice-server  |   File "/app/fam/llm/serving.py", line 105, in text_to_speech
metavoice-server  |     wav_out_path = sample_utterance(
metavoice-server  |                    ^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/app/fam/llm/sample.py", line 546, in sample_utterance
metavoice-server  |     return _sample_utterance_batch(
metavoice-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/app/fam/llm/sample.py", line 466, in _sample_utterance_batch
metavoice-server  |     spk_cond_paths = tqdm.contrib.concurrent.thread_map(
metavoice-server  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
metavoice-server  |     return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
metavoice-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
metavoice-server  |     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
metavoice-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
metavoice-server  |     for obj in iterable:
metavoice-server  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
metavoice-server  |     yield _result_or_cancel(fs.pop())
metavoice-server  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
metavoice-server  |     return fut.result(timeout)
metavoice-server  |            ^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
metavoice-server  |     return self.__get_result()
metavoice-server  |            ^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
metavoice-server  |     raise self._exception
metavoice-server  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
metavoice-server  |     result = self.fn(*self.args, **self.kwargs)
metavoice-server  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-server  |   File "/app/fam/llm/sample.py", line 412, in get_cached_file
metavoice-server  |     subprocess.run(command, shell=True, check=True)
metavoice-server  |   File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
metavoice-server  |     raise CalledProcessError(retcode, process.args,
metavoice-server  | subprocess.CalledProcessError: Command 'curl -o /root/.cache/fam/audio_8d3be3b719f3973cd4e3d59de13a26c4.flac https://cdn.themetavoice.xyz/speakers/ava.flac' returned non-zero exit status 127.
metavoice-server  | INFO:     172.22.0.3:42550 - "POST /tts HTTP/1.1" 500 Internal Server Error
metavoice-ui      | Something went wrong. response status code: 500
metavoice-ui      | Traceback (most recent call last):
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
metavoice-ui      |     output = await route_utils.call_process_api(
metavoice-ui      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/route_utils.py", line 231, in call_process_api
metavoice-ui      |     output = await app.get_blocks().process_api(
metavoice-ui      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1600, in process_api
metavoice-ui      |     data = self.postprocess_data(fn_index, result["prediction"], state)
metavoice-ui      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1452, in postprocess_data
metavoice-ui      |     prediction_value = block.postprocess(prediction_value)
metavoice-ui      |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/components/audio.py", line 253, in postprocess
metavoice-ui      |     file_path = processing_utils.save_audio_to_cache(
metavoice-ui      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metavoice-ui      |   File "/usr/local/lib/python3.11/site-packages/gradio/processing_utils.py", line 152, in save_audio_to_cache
metavoice-ui      |     temp_dir = Path(cache_dir) / hash_bytes(data.tobytes())
metavoice-ui      |                                             ^^^^^^^^^^^^
metavoice-ui      | AttributeError: 'NoneType' object has no attribute 'tobytes'
```

**Comment by sidroopdaska** [comment]
please pull from `main` again, we have pushed a few changes since you last forked

**Comment by groovybits** [comment]
FYI: I can get it building with my Mac native now, when running I run into this issue. The docker seems to give the previous mentioned error so looks more docker specific on that problem. I suspect this may be an issue with it on MPS still?

---
If your task is similar to the task the model of the checkpoint was trained on, you can already use EncodecModel for predictions without further training.
2024-02-13 14:09:01 | INFO     | DF | Running on torch 2.1.0
2024-02-13 14:09:01 | INFO     | DF | Running on host earth.local
2024-02-13 14:09:01 | INFO     | DF | Git commit: eb7338abb, branch: stable
2024-02-13 14:09:01 | INFO     | DF | Loading model settings of DeepFilterNet3
2024-02-13 14:09:01 | INFO     | DF | Using DeepFilterNet3 model at /Users/chris/Library/Caches/DeepFilterNet/DeepFilterNet3
2024-02-13 14:09:01 | INFO     | DF | Initializing model `deepfilternet3`
2024-02-13 14:09:01 | INFO     | DF | Found checkpoint /Users/chris/Library/Caches/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2024-02-13 14:09:01 | INFO     | DF | Running on device cpu
2024-02-13 14:09:01 | INFO     | DF | Model loaded
INFO:     Started server process [73304]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:58003 (Press CTRL+C to quit)
getting cached speaker ref files:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s][src/libmpg123/id3.c:INT123_id3_to_utf8():394] warning: Weird tag size 101 for encoding 1 - I will probably trim too early or something but I think the MP3 is broken.
getting cached speaker ref files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.16it/s]
calculating speaker embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1116.99it/s]
batch:   0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Error processing request {'text': 'Test 123', 'guidance': 3.0, 'top_p': 0.95, 'speaker_ref_path': 'https://cdn.themetavoice.xyz/speakers/bria.mp3'}
Traceback (most recent call last):
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/serving.py", line 105, in text_to_speech
    wav_out_path = sample_utterance(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 546, in sample_utterance
    return _sample_utterance_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 477, in _sample_utterance_batch
    b_tokens = first_stage_model(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 356, in __call__
    return self.causal_sample(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 231, in causal_sample
    y = self.model.generate(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/model.py", line 369, in generate
    return self._causal_sample(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/mixins/causal.py", line 392, in _causal_sample
    if guidance_scale[1] > 1:
       ~~~~~~~~~~~~~~^^^
TypeError: 'float' object is not subscriptable
INFO:     192.168.50.55:51261 - "POST /tts HTTP/1.1" 500 Internal Server Error
---

Seems the guidance scale part is not as expected, I tried to

**Comment by vatsalaggarwal** [comment]
Guidance scale should be (3.0, 1.0)... what is it currently set to?

**Comment by djmaze** [comment]
It seems the `denormalize_guidance` function is broken, it returns a single value instead of a tuple.

**Comment by groovybits** [comment]
I am using fam/ui/app.py with the defaults it sets, it seems to be trying to use a decimal, yet I can't see how to fix that anywhere.

**Comment by djmaze** [comment]
The ui sends the "Speaker similarity" value as a single float instead of a tuple. I just changed line 66 to `"guidance": [d_guidance, 1.0],` which seems to have made it work for me. (Not sure if it makes sense like this though.)

**Comment by vatsalaggarwal** [comment]
@pyetras

**Comment by djmaze** [comment]
On another note, choosing any preset voice other than `Bria` is not working because the other samples are shorter than 30s.

**Comment by sidroopdaska** [comment]
give me a few mins to fix this.

**Comment by sidroopdaska** [comment]
Done, please try now

**Comment by groovybits** [comment]
I'm seeing this now after getting past the past issues, this is on mps m2 ultra, guessing it can't install the flash-attn module hence the part of it that would work isn't loaded... 

```
2024-02-13 16:52:44 | INFO     | DF | Running on torch 2.1.0
2024-02-13 16:52:44 | INFO     | DF | Running on host earth.local
2024-02-13 16:52:44 | INFO     | DF | Git commit: eb7338abb, branch: stable
2024-02-13 16:52:44 | INFO     | DF | Loading model settings of DeepFilterNet3
2024-02-13 16:52:44 | INFO     | DF | Using DeepFilterNet3 model at /Users/chris/Library/Caches/DeepFilterNet/DeepFilterNet3
2024-02-13 16:52:44 | INFO     | DF | Initializing model `deepfilternet3`
2024-02-13 16:52:44 | INFO     | DF | Found checkpoint /Users/chris/Library/Caches/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2024-02-13 16:52:44 | INFO     | DF | Running on device cpu
2024-02-13 16:52:44 | INFO     | DF | Model loaded
INFO:     Started server process [77674]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:58003 (Press CTRL+C to quit)
getting cached speaker ref files:   0%|                                                                                                                                                     | 0/1 [00:00<?, ?it/s][src/libmpg123/id3.c:INT123_id3_to_utf8():394] warning: Weird tag size 101 for encoding 1 - I will probably trim too early or something but I think the MP3 is broken.
getting cached speaker ref files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.21it/s]
calculating speaker embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1099.14it/s]
batch:   0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s][hack!!!!] Guidance is on, so we're doubling/tripling batch size!                                                                                                                        | 0/1728 [00:00<?, ?it/s]
tokens:   0%|                                                                                                                                                                            | 0/1728 [00:00<?, ?it/s]
batch:   0%|                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Error processing request {'text': 'This is a demo of text to speech by MetaVoice-1B, an open-source foundational audio model by MetaVoice.', 'guidance': [3.0, 1.0], 'top_p': 0.95, 'speaker_ref_path': 'https://cdn.themetavoice.xyz/speakers/bria.mp3'}
Traceback (most recent call last):
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/serving.py", line 105, in text_to_speech
    wav_out_path = sample_utterance(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 546, in sample_utterance
    return _sample_utterance_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 477, in _sample_utterance_batch
    b_tokens = first_stage_model(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 356, in __call__
    return self.causal_sample(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/sample.py", line 231, in causal_sample
    y = self.model.generate(
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/model.py", line 369, in generate
    return self._causal_sample(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/mixins/causal.py", line 410, in _causal_sample
    batch_idx = self._sample_batch(
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/mixins/causal.py", line 264, in _sample_batch
    idx_next = self._sample_next_token(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/mixins/causal.py", line 85, in _sample_next_token
    list_logits, _ = self(
                     ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/model.py", line 282, in forward
    x = block(x)
        ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/layers/combined.py", line 50, in forward
    x = x + self.attn(self.ln_1(x))
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/layers/attn.py", line 291, in forward
    y = self._fd_attention(c_x)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/code/rsllm/metavoice-src-groovybits/fam/llm/layers/attn.py", line 191, in _fd_attention
    y = flash_attn_with_kvcache(
        ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'flash_attn_with_kvcache' is not defined
INFO:     127.0.0.1:57688 - "POST /tts HTTP/1.1" 500 Internal Server Error
```

**Comment by djmaze** [comment]
Thanks, I can test again later today. Concerning flash_attn, yeah it seems to me that it is currently required. So I added `pip install packaging` and `pip install flash-attn` to my dockerfile which made it work for me.

**Comment by djmaze** [comment]
> Done, please try now

Thanks, it works now. (Wondering what looping the reference audio does to the quality though..)

**Comment by djmaze** [comment]
I also realized that there is already a PR open for docker support in #17. We should probably join forces over there?

**Comment by sidroopdaska** [comment]
> (Wondering what looping the reference audio does to the quality though..)

Haha, I did this as a stop-gap until we release a more extensive palette of preset voices in a couple of days.
I haven't seen artefacts being introduced from looping these two voices. If you notice something peculiar, then please do share.

**Comment by sidroopdaska** [comment]
> I also realized that there is already a PR open for docker support in https://github.com/metavoiceio/metavoice-src/pull/17. We should probably join forces over there?

Yes, please!

**Comment by groovybits** [comment]
> > I also realized that there is already a PR open for docker support in #17. We should probably join forces over there?
> 
> Yes, please!

Definitely agree, this was more of an exercise in getting it working. I think I now am dealing with metal/mps issues beyond basic dockerization (and seems metal/mps can't pass the GPU through docker which may explain my 139 error in the docker). Outside of the docker on my metal/mps mac I run into the lack of flash_attn packages.

**Comment by l4b4r4b4b4** [comment]
> > > I also realized that there is already a PR open for docker support in #17. We should probably join forces over there?
> > 
> > 
> > Yes, please!
> 
> Definitely agree, this was more of an exercise in getting it working. I think I now am dealing with metal/mps issues beyond basic dockerization (and seems metal/mps can't pass the GPU through docker which may explain my 139 error in the docker). Outside of the docker on my metal/mps mac I run into the lack of flash_attn packages.

the docker implementation i did should work fine with CUDA GPU-acceleration on any system...
