### ISSUE TITLE
Error during installation of deps

### ISSUE THREAD

**Issue by Subuday** [metavoiceio/metavoice-src#74]
Any suggestion to fix this error?

```
Collecting xformers
  Using cached xformers-0.0.23.post1-cp310-cp310-manylinux2014_x86_64.whl (213.0 MB)
  Using cached xformers-0.0.23-cp310-cp310-manylinux2014_x86_64.whl (213.0 MB)
  Using cached xformers-0.0.22.post7-cp310-cp310-manylinux2014_x86_64.whl (211.8 MB)
  Using cached xformers-0.0.22-cp310-cp310-manylinux2014_x86_64.whl (211.6 MB)
  Using cached xformers-0.0.21-cp310-cp310-manylinux2014_x86_64.whl (167.0 MB)
  Using cached xformers-0.0.20-cp310-cp310-manylinux2014_x86_64.whl (109.1 MB)
  Using cached xformers-0.0.19-cp310-cp310-manylinux2014_x86_64.whl (108.2 MB)
Collecting pyre-extensions==0.0.29
  Using cached pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Collecting xformers
  Using cached xformers-0.0.18-cp310-cp310-manylinux2014_x86_64.whl (123.8 MB)
Collecting pyre-extensions==0.0.23
  Using cached pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting xformers
  Using cached xformers-0.0.17-cp310-cp310-manylinux2014_x86_64.whl (123.6 MB)
  Using cached xformers-0.0.16-cp310-cp310-manylinux2014_x86_64.whl (50.9 MB)
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mu60tz0e/xformers_4aa19d62bcc44da58b0f254d6573d196/setup.py", line 18, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by sidroopdaska** [comment]
Can you share the commands you ran leading upto this error please?

**Comment by Subuday** [comment]
Commands are from your Environment setup.

**Comment by Subuday** [comment]
For running the code, I used RunPod instance with Python 3.10 and Cuda 11.8.0.
Deps are installed using python virt env.

**Comment by vatsalaggarwal** [comment]
Sorry, a bit unsure what's going on here... 

Can you run the following and give us the results please?
```bash
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
(for security, reference of this is from [PyTorch bug reporting template](https://github.com/pytorch/pytorch/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml?plain=1))

by the way, I've always had some issue getting torch/torch dependencies working on runpod :( can you try somewhere else like vast.ai or jarvis cloud?

**Comment by Subuday** [comment]
@vatsalaggarwal it looks like that error is raised if deps is installed using virtual env.
When I install deps using system python, it's fine. I've attached logs while it's virtual env:
[env_info.txt](https://github.com/metavoiceio/metavoice-src/files/14464204/env_info.txt)

**Comment by shershah1024** [comment]
Had exactly the same issue on Runpod. @Subuday : Were you able to get it running after installing with system python?

**Comment by shershah1024** [comment]
Taking my question back. I managed to run it on Runpod. Not using the venv worked. Thank you

**Comment by vatsalaggarwal** [comment]
I think this is a runpod specific issue, with the resolution being to not use venv, so I'm going to close this issue.
