### ISSUE TITLE
Changing the seed does nothing.

### ISSUE THREAD

**Issue by arthurwolf** [metavoiceio/metavoice-src#86]
It generates the exact same wav file no matter what seed I input, no variation (that I can notice).

Any idea why?

I'm using fast_inference.py, just modified enough to take command line parameters (including the seed):

```
# Import required modules for file and system operations
import os
import grp
import pwd
import shutil
import tempfile
import time
from pathlib import Path

# Import the random module
import random 

# Import argparse for command-line argument parsing
import argparse

# Import necessary libraries for audio processing and deep learning
import librosa
import torch
from huggingface_hub import snapshot_download

# Import specific classes and functions from the project's modules
from fam.llm.adapters import FlattenedInterleavedEncodec2Codebook
from fam.llm.decoders import EncodecDecoder
from fam.llm.fast_inference_utils import build_model, main
from fam.llm.inference import (
    EncodecDecoder,
    InferenceConfig,
    Model,
    TiltedEncodec,
    TrainedBPETokeniser,
    get_cached_embedding,
    get_cached_file,
    get_enhancer,
)
from fam.llm.utils import (
    check_audio_file,
    get_default_dtype,
    get_device,
    normalize_text,
)

# Define a function to parse command-line arguments
def parse_args():
    parser = argparse.ArgumentParser(description='Text-to-Speech using the specified model.')
    parser.add_argument('--text', type=str, required=True, help='Text to convert to speech.')
    parser.add_argument('--spk_ref_path', type=str, required=True, help='Path to speaker reference audio file. Minimum 30 seconds of audio required.')
    parser.add_argument('--top_p', type=float, default=0.95, help='Top p for sampling. Range [0.9, 1.0]. A measure of speech stability.')
    parser.add_argument('--guidance_scale', type=float, default=3.0, help='Guidance scale for sampling. Range [1.0, 3.0]. A measure of speaker similarity.')
    parser.add_argument('--temperature', type=float, default=1.0, help='Temperature for sampling. Applied to both LLMs.')
    parser.add_argument('--output_dir', type=str, default="outputs", help='Directory to save the output speech files.')
    parser.add_argument('--seed', type=int, default=None, help='Seed for reproducibility (default/if none is provided: generate a random seed).')
    return parser.parse_args()  # Return the parsed arguments

# Define a class for the Text-to-Speech (TTS) functionality
class TTS:
    
    # Define a constant for the end-of-audio token
    END_OF_AUDIO_TOKEN = 1024

    # Initialize the TTS object with model information and output directory
    def __init__(
        self, model_name: str = "metavoiceio/metavoice-1B-v0.1", *, seed: int = None, output_dir: str = "outputs"
    ):

        # Check if seed is None and generate a random seed between 0 and 2000 if true
        if seed is None:
            seed = random.randint(0, 2000)

        # Display the seed.
        print(f"Seed: {seed}")

        # Set the default data type and device for PyTorch operations
        self._dtype = get_default_dtype()
        self._device = get_device()

        # Download the model directory from Hugging Face Hub
        self._model_dir = snapshot_download(repo_id=model_name)

        # Initialize the first stage adapter with the end-of-audio token
        self.first_stage_adapter = FlattenedInterleavedEncodec2Codebook(end_of_audio_token=self.END_OF_AUDIO_TOKEN)

        # Set the output directory and create it if it doesn't exist
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

        # Configure and initialize the second stage of the model
        second_stage_ckpt_path = f"{self._model_dir}/second_stage.pt"
        config_second_stage = InferenceConfig(
            ckpt_path=second_stage_ckpt_path,
            num_samples=1,
            seed=seed,
            device=self._device,
            dtype=self._dtype,
            compile=False,
            init_from="resume",
            output_dir=self.output_dir,
        )

        # Initialize the data adapter for the second stage
        data_adapter_second_stage = TiltedEncodec(end_of_audio_token=self.END_OF_AUDIO_TOKEN)

        # Create the model for the second stage
        self.llm_second_stage = Model(
            config_second_stage, TrainedBPETokeniser, EncodecDecoder, data_adapter_fn=data_adapter_second_stage.decode
        )

        # Initialize the audio enhancer
        self.enhancer = get_enhancer("df")

        # Set the precision for the model based on the specified data type
        self.precision = {"float16": torch.float16, "bfloat16": torch.bfloat16}[self._dtype]

        # Build the model, tokenizer, and speaker model, and get the model size
        self.model, self.tokenizer, self.smodel, self.model_size = build_model(
            precision=self.precision,
            checkpoint_path=Path(f"{self._model_dir}/first_stage.pt"),
            spk_emb_ckpt_path=Path(f"{self._model_dir}/speaker_encoder.pt"),
            device=self._device,
            compile=True,
            compile_prefill=True,
        )

    # Define the method to synthesize speech from text
    def synthesise(self, text: str, spk_ref_path: str, top_p=0.95, guidance_scale=3.0, temperature=1.0) -> str:

        # Normalize the input text
        text = normalize_text(text)

        # Get the cached file for the speaker reference path
        spk_ref_path = get_cached_file(spk_ref_path)

        # Check if the audio file is valid
        check_audio_file(spk_ref_path)

        # Get the cached speaker embedding
        spk_emb = get_cached_embedding(
            spk_ref_path,
            self.smodel,
        ).to(device=self._device, dtype=self.precision)

        # Record the start time for synthesis
        start = time.time()
        # Generate tokens using the first stage LLM
        tokens = main(
            model=self.model,
            tokenizer=self.tokenizer,
            model_size=self.model_size,
            prompt=text,
            spk_emb=spk_emb,
            top_p=torch.tensor(top_p, device=self._device, dtype=self.precision),
            guidance_scale=torch.tensor(guidance_scale, device=self._device, dtype=self.precision),
            temperature=torch.tensor(temperature, device=self._device, dtype=self.precision),
        )
        # Decode the extracted audio IDs from the tokens
        _, extracted_audio_ids = self.first_stage_adapter.decode([tokens])

        # Prepare speaker embeddings for batch processing
        b_speaker_embs = spk_emb.unsqueeze(0)

        # Generate waveform files using the second stage LLM and multi-band diffusion model
        wav_files = self.llm_second_stage(
            texts=[text],
            encodec_tokens=[torch.tensor(extracted_audio_ids, dtype=torch.int32, device=self._device).unsqueeze(0)],
            speaker_embs=b_speaker_embs,
            batch_size=1,
            guidance_scale=None,
            top_p=None,
            top_k=200,
            temperature=1.0,
            max_new_tokens=None,
        )

        # Enhance the generated waveform using DeepFilterNet
        wav_file = wav_files[0]
        
        # Print the type of wav_file.
        with tempfile.NamedTemporaryFile(suffix=".wav") as enhanced_tmp:

            # Print enhanced_tmp.name
            self.enhancer(str(wav_file) + ".wav", enhanced_tmp.name)
            shutil.copy2(enhanced_tmp.name, str(wav_file) + ".wav")
            print(f"\nSaved audio to {wav_file}.wav")

            # Copy the enhanced audio to the output directory
            output_file = self.output_dir + "/output.wav"
            shutil.copy2(enhanced_tmp.name, output_file)

            # Set the synthesized speech file's permissions so it's readable and writable by everyone
            os.chmod(output_file, 0o666)
            
            # Change the ownership of the synthesized speech file to user and group with ID 1000
            # Note: This operation requires superuser privileges
            user_id = 1000
            group_id = 1000
            os.chown(output_file, user_id, group_id)


        # Calculate the real-time factor (RTF) of the synthesis process
        time_to_synth_s = time.time() - start
        audio, sr = librosa.load(str(wav_file) + ".wav")
        duration_s = librosa.get_duration(y=audio, sr=sr)
        print(f"\nTotal time to synth (s): {time_to_synth_s}")
        print(f"Real-time factor: {time_to_synth_s / duration_s:.2f}")

        # Return the path to the synthesized speech file
        return str(wav_file) + ".wav"

# Check if this script is the main program and execute the main logic
if __name__ == "__main__":

    # Parse command-line arguments
    args = parse_args()

    # Initialize the TTS system with the output directory
    tts = TTS(output_dir=args.output_dir, seed=args.seed)

    # Synthesize speech from the provided text and speaker reference
    synthesized_speech_path = tts.synthesise(text=args.text, spk_ref_path=args.spk_ref_path, top_p=args.top_p, guidance_scale=args.guidance_scale, temperature=args.temperature)

    # Output the path to the synthesized speech
    print(f"Synthesized speech saved to: {synthesized_speech_path}")

    # Set the synthesized speech file's permissions so it's readable and writable by everyone
    os.chmod(synthesized_speech_path, 0o666)
    
    # Change the ownership of the synthesized speech file to user and group with ID 1000
    # Note: This operation requires superuser privileges
    user_id = 1000
    group_id = 1000
    os.chown(synthesized_speech_path, user_id, group_id)


```

**Comment by vatsalaggarwal** [comment]
Sounds like a bug! Will try to trace it down in a bit, but most likely seed isn't being propagated properly?

----

Temperature - 0 to 1
top_p - also 0 to 1
Guidance - 1 to 3

**Comment by arthurwolf** [comment]
Thanks a lot for the answer.

I'm off to bed now, but if you don't fix this by friday, at that point I'll try to follow the variable through the code and see if I find where it's broken.

Additional info: it generates the same files, to the bit:

```
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-0-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-0-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-10-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-10-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-11-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-11-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-1-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-1-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-2-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-2-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-3-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-3-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-4-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-4-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-5-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-5-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-6-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-6-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-7-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-7-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-8-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-8-vocals.wav
fdc1403342e691b0beb2f8bb0b64486c  /ram/read-9-base.wav
2ae585c28ec2c3b9b1286c6ef0fbb69d  /ram/read-9-vocals.wav
```

**Comment by vatsalaggarwal** [comment]
I don't think I'll have the time before the weekend either

**Comment by vatsalaggarwal** [comment]
- ugh, sorry about that! I've just searched for "seed(" throughout our codebase, and that seems like the only culprit.
- sorry about this... here is the relevant section: https://github.com/metavoiceio/metavoice-src?tab=readme-ov-file#usagehttps://github.com/metavoiceio/metavoice-src?tab=readme-ov-file#usage ... yes, it has no command line params, we're expecting people to use it in interactive mode. (reason: this is a faster version that uses a "compiled" model... compilation can take up to 2 minutes, and so there's no point in having a cli version that restarts the python process everytime as you'll have to pay for compilation again).
- re: the difference between `inference.py` and `fast_inference.py`, the latter is the compiled version and used in the interactive mode as above. `inference.py` doesn't do compilation and doesn't have all the inference optimisations, but critically doesn't use compilation, so it can be used in cli form...

we haven't had the chance to improve this experience yet :)

**Comment by arthurwolf** [comment]
> we haven't had the chance to improve this experience yet
would you be interrested in a PR with a few changes to code and docs?

a few more questions:
* fast_inference seems to generate more "garbled" speech than the online demo I found (replicate?). is this about parameters? or does it use a different model? what's going on there?
* in case that would help, I'm trying to use inference.py, but that runs out of VRAM it seems (I'm on a 12GB card with about 10GB free), what's the size of the fast and non-fast models in VRAM? I tried running with --cpu so VRAM is no longer a concern, and I get:

```
Fetching 6 files: 100%|██████████| 6/6 [00:00<00:00, 140591.20it/s]
number of parameters: 1239.00M
number of parameters: 14.07M
getting cached speaker ref files: 100%|██████████| 1/1 [00:00<00:00, 19065.02it/s]
calculating speaker embeddings: 100%|██████████| 1/1 [00:00<00:00,  2.18it/s]
tokens:   0%|          | 0/1728 [00:00<?, ?it/s]
batch:   0%|          | 0/1 [00:00<?, ?it/s]t/s]
[hack!!!!] Guidance is on, so we're doubling/tripling batch size!
Traceback (most recent call last):
  File "/app/fam/llm/inference.py", line 700, in <module>
    sample_utterance(
  File "/app/fam/llm/inference.py", line 543, in sample_utterance
    return _sample_utterance_batch(
  File "/app/fam/llm/inference.py", line 472, in _sample_utterance_batch
    b_tokens = first_stage_model(
  File "/app/fam/llm/inference.py", line 354, in __call__
    return self.causal_sample(
  File "/app/fam/llm/inference.py", line 229, in causal_sample
    y = self.model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/fam/llm/model.py", line 369, in generate
    return self._causal_sample(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/fam/llm/mixins/causal.py", line 410, in _causal_sample
    batch_idx = self._sample_batch(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/fam/llm/mixins/causal.py", line 264, in _sample_batch
    idx_next = self._sample_next_token(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/fam/llm/mixins/causal.py", line 85, in _sample_next_token
    list_logits, _ = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/fam/llm/model.py", line 282, in forward
    x = block(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/fam/llm/layers/combined.py", line 50, in forward
    x = x + self.attn(self.ln_1(x))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/fam/llm/layers/attn.py", line 178, in forward
    y = self._torch_attn(c_x)
  File "/app/fam/llm/layers/attn.py", line 148, in _torch_attn
    y = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: c10::BFloat16 and value.dtype: c10::BFloat16 instead.
```

**Comment by vatsalaggarwal** [comment]
> would you be interrested in a PR with a few changes to code and docs?

yes, that would be great!

> fast_inference seems to generate more "garbled" speech than the online demo I found (replicate?). is this about parameters? or does it use a different model? what's going on there?

that's weird, first time we've heard that... can you send me the link to the online demo you're talking about? it's likely that you ended up coming across a bad seed or that the online demo you're referring to is using a different reference speaker (garbling/artefacts/etc are super sensitive to the reference you use), but let me just double check once i have the link!

> in case that would help, I'm trying to use inference.py, but that runs out of VRAM it seems (I'm on a 12GB card with about 10GB free), what's the size of the fast and non-fast models in VRAM? I tried running with --cpu so VRAM is no longer a concern, and I get

I don't how well torch supports compilation on CPU, etc, so I probably wouldn't debug this on CPU. I think the fast version should use slightly more memory than non-fast (they are the exact same model, just difference in overheads). For fitting it on 12GB, I would recommend swapping out the diffusion model for the Vocos model. You could additionally try quantisation for the first stage model.

> `RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: c10::BFloat16 and value.dtype: c10::BFloat16 instead.`

Think either the `device` or `dtypes` aren't being passed around correctly, will need to be tracked down. Note that I don't think CPUs support `bfloat16` calculation, so this is unlikely to work regardless

**Comment by arthurwolf** [comment]
> can you send me the link to the online demo you're talking about?

https://ttsdemo.themetavoice.xyz/

Two issues:
1. There are two sliders, and they don't seem to match the parameters in `inference.py` and `fast_inference.py` (both in terms of names and min/max values).
2. The page doesn't really say what model/script is used behind the scene.

I get better output from that demo than from running it locally, so I'd really like some way to reproduce what that page does.

> you ended up coming across a bad seed 

Consistently bad across 16 tries. I'll do some demo/reproduction later on to show you.

> garbling/artefacts/etc

The sample is pretty clean, and works better in the online demo / with xtts (https://huggingface.co/spaces/coqui/xtts).

>  I would recommend swapping out the diffusion model for the Vocos model.

Is that trivial, or more involved? I'm a user of AI stuff, not really a designer of it. Too few PHDs (ie zero).

> You could additionally try quantisation for the first stage model.

Same question.

Is there something, anything, I can do using the command line parameters, or some simple modification of the code, that would result in lower VRAM usage?

> I don't how well torch supports compilation on CPU,

In my experience with other projects it's always been fine.

I was able to fully run inference.py on CPU with compilation enabled and with it disabled, so your code/project is better than you presumed :) Took 25 minutes though.

Note, even with `--device cpu`, inference.py still used 4.5GB of VRAM. That means `--device` is propagated only to some parts of the code?

>  I think the fast version should use slightly more memory than non-fast (they are the exact same model, just difference in overheads).

On my machine, the fast version runs fine on the GPU, the slow version doesn't. Is there some way to know how much each "requires"/needs ? I'd like to know what (minimum) size GPU I need to buy for this to work. 

> Note that I don't think CPUs support bfloat16 calculation, so this is unlikely to work regardless

I was able to get it to work, on cpu, by setting `--dtype float32`.


PS: Question: the docs say 45-90 seconds for the sample. Mine is 50 seconds. Should I expect better results with a 90 seconds one? Would a 5 minute sample do even better (even if by a little) than a 90 second one?

**Comment by vatsalaggarwal** [comment]
> There are two sliders, and they don't seem to match the parameters in inference.py and fast_inference.py (both in terms of names and min/max values).

Yep, we've scaled the top_p and guidance_scale parameters to make them more convenient. See https://github.com/metavoiceio/metavoice-src/blob/main/app.py#L29-L36 for reference.

> Consistently bad across 16 tries

Just to double check, did a new seed get used on each try? It's possible each try ended up using the same seed...

> I'll do some demo/reproduction later on to show you.

this would be super helpful!

re the rest:
- would say that swapping out vocos for mbd might take some work
- different guidance_scale values should not impact VRAM usage
- yeah, it looks like `device` isn't being propagated properly... i think one of the draft PRs currently open fixes this but it is lagging behind main unfortunately
- We recommend a GPU with 24GB VRAM minimum, and don't internally test on GPUs below that spec.
- float16 should also work fine on CPU, and might speed you up?
- hard to know what's going on with the samples... if you can share it with me at vatsal@themetavoice.xyz that's ideal! longer samples can help, but quality/compression of the sample is equally important.
